from config import (
    EXTRACT_RETAIL_SAMPLE_ECOMMERCE_SPEC,
    EXTRACT_RETAIL_SAMPLE_SPEC,
    FIELD_SAMPLE_EVENTS_NESTED_PATH,
    FIELD_SAMPLE_JSONO_COMPRESSION,
    FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
    FIELD_SAMPLE_JSONO_EVENTS_PATH,
    FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
    FIELD_SAMPLE_ROW_COUNT,
    FIELD_SAMPLE_RULES_PATH,
    FIELD_SAMPLE_STRUCT_CORE_SPEC,
    FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
    RESULTS_DIR,
    RETAIL_SAMPLE_ECOMMERCE_PARSE_COPY_PATH,
    RETAIL_SAMPLE_ECOMMERCE_PATH,
    RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
    RETAIL_SAMPLE_EVENTS_PATH,
    RETAIL_SAMPLE_PARSE_COPY_PATH,
    RETAIL_SAMPLE_ROW_COUNT,
)

FIELD_SAMPLE_SCENARIOS = [
    {
        "operation": "scan_text",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "current_only": True,
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "copy_path": RESULTS_DIR / "field_sample_parse_copy.parquet",
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_roundtrip",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_json_roundtrip",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_jsono",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_json",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_roundtrip",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_json_roundtrip",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_jsono",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_json",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "transform",
        "scenario": "field_sample_rules",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_JSONO_EVENTS_PATH,
        "rules_file": FIELD_SAMPLE_RULES_PATH,
        "jsono_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "copy_path": RETAIL_SAMPLE_PARSE_COPY_PATH,
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "extract",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "spec": EXTRACT_RETAIL_SAMPLE_SPEC,
        "targets": ["jsono", "json"],
    },
    {
        "operation": "merge_patch",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "patch_object": {"event_name": "page_view"},
        "targets": ["jsono", "json"],
    },
    {
        "operation": "entries",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge",
        "scenario": "retail_sample_clientid",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "group_col": "group_id",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge_jsono",
        "scenario": "retail_sample_clientid",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "group_col": "group_id",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "copy_path": RETAIL_SAMPLE_ECOMMERCE_PARSE_COPY_PATH,
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "merge_patch",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "patch_object": {"event_name": "ecommerce purchase"},
        "targets": ["jsono", "json"],
    },
    {
        "operation": "entries",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "extract",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "spec": EXTRACT_RETAIL_SAMPLE_ECOMMERCE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
]
