from config import (
    EXTRACT_RETAIL_SAMPLE_ECOMMERCE_SPEC,
    EXTRACT_RETAIL_SAMPLE_SPEC,
    FIELD_SAMPLE_EVENTS_NESTED_PATH,
    FIELD_SAMPLE_FILTER_PREDICATES,
    FIELD_SAMPLE_JSONO_COMPRESSION,
    FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
    FIELD_SAMPLE_JSONO_EVENTS_PATH,
    FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
    FIELD_SAMPLE_PROJECT_PATHS,
    FIELD_SAMPLE_ROW_COUNT,
    FIELD_SAMPLE_RULES_PATH,
    FIELD_SAMPLE_SHREDDING_SPEC,
    FIELD_SAMPLE_STRUCT_CORE_SPEC,
    FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
    RESULTS_DIR,
    RETAIL_SAMPLE_ECOMMERCE_PARSE_COPY_PATH,
    RETAIL_SAMPLE_ECOMMERCE_PATH,
    RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
    RETAIL_SAMPLE_EVENTS_PATH,
    RETAIL_SAMPLE_PARSE_COPY_PATH,
    RETAIL_SAMPLE_ROW_COUNT,
)

FIELD_SAMPLE_SCENARIOS = [
    {
        "operation": "scan_text",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "current_only": True,
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "copy_path": RESULTS_DIR / "field_sample_parse_copy.parquet",
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_plain",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_roundtrip",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_json_roundtrip",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_jsono",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_json",
        "scenario": "field_sample_typed_core",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_plain",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_roundtrip",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_json_roundtrip",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_jsono",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "object_json",
        "scenario": "field_sample_typed_products",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "struct_spec": FIELD_SAMPLE_STRUCT_PRODUCTS_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "transform",
        "scenario": "field_sample_rules",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_JSONO_EVENTS_PATH,
        "rules_file": FIELD_SAMPLE_RULES_PATH,
        "jsono_column": "event_properties",
        "targets": ["jsono"],
    },
    # Shredded coverage: shred-from-text ingest, reads over a shredded column
    # (shred-hit, residual miss, container path), transform, and filterless
    # multi-extract projections (plain vs shredded, O-1/O-2). Reads materialize
    # the shredded jsono before the timed section; parse_shred is the only
    # end-to-end case.
    {
        "operation": "parse_shred",
        "scenario": "field_sample_nested",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "extract_string",
        "scenario": "field_sample_shred_hit",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "path": "$.clientID",
        "targets": ["jsono"],
    },
    {
        "operation": "extract_string",
        "scenario": "field_sample_shred_miss",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "path": "$.browser",
        "targets": ["jsono"],
    },
    {
        "operation": "extract_jsono",
        "scenario": "field_sample_shred_container",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "path": "$.products",
        "targets": ["jsono"],
    },
    {
        "operation": "transform",
        "scenario": "field_sample_rules_shredded",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "rules_file": FIELD_SAMPLE_RULES_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "project_paths",
        "scenario": "field_sample_plain",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "paths": FIELD_SAMPLE_PROJECT_PATHS,
        "targets": ["jsono", "json"],
    },
    {
        "operation": "project_paths",
        "scenario": "field_sample_shredded",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "paths": FIELD_SAMPLE_PROJECT_PATHS,
        "targets": ["jsono"],
    },
    {
        "operation": "filter_paths",
        "scenario": "field_sample_plain",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "predicates": FIELD_SAMPLE_FILTER_PREDICATES,
        "targets": ["jsono", "json"],
    },
    {
        "operation": "filter_paths",
        "scenario": "field_sample_shredded",
        "size": "245760",
        "row_count": FIELD_SAMPLE_ROW_COUNT,
        "data_file": FIELD_SAMPLE_EVENTS_NESTED_PATH,
        "json_column": "event_properties",
        "shredding": FIELD_SAMPLE_SHREDDING_SPEC,
        "predicates": FIELD_SAMPLE_FILTER_PREDICATES,
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "copy_path": RETAIL_SAMPLE_PARSE_COPY_PATH,
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "extract",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "spec": EXTRACT_RETAIL_SAMPLE_SPEC,
        "targets": ["jsono", "json"],
    },
    {
        "operation": "merge_patch",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "patch_object": {"event_name": "page_view"},
        "targets": ["jsono", "json"],
    },
    {
        "operation": "entries",
        "scenario": "retail_sample_nested",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "entries",
        "scenario": "retail_sample_nested_whole",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "array_style": "whole_json",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge",
        "scenario": "retail_sample_clientid",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "group_col": "group_id",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge_jsono",
        "scenario": "retail_sample_clientid",
        "size": "245760",
        "row_count": RETAIL_SAMPLE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_EVENTS_PATH,
        "json_column": "event_properties",
        "group_col": "group_id",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "copy_path": RETAIL_SAMPLE_ECOMMERCE_PARSE_COPY_PATH,
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "merge_patch",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "patch_object": {"event_name": "ecommerce purchase"},
        "targets": ["jsono", "json"],
    },
    {
        "operation": "entries",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
    {
        "operation": "entries",
        "scenario": "retail_sample_ecommerce_whole",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "array_style": "whole_json",
        "targets": ["jsono"],
    },
    {
        "operation": "extract",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "spec": EXTRACT_RETAIL_SAMPLE_ECOMMERCE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "retail_sample_ecommerce",
        "size": "65987",
        "row_count": RETAIL_SAMPLE_ECOMMERCE_ROW_COUNT,
        "data_file": RETAIL_SAMPLE_ECOMMERCE_PATH,
        "json_column": "event_properties",
        "targets": ["jsono"],
    },
]
