from config import (
    DATA_DIR,
    EXTRACT_CORE_SPEC,
    FIELD_SAMPLE_JSONO_COMPRESSION,
    FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
    FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
    NUMBERS_PARSE_COPY_PATH,
    NUMBERS_SIZES,
    PLUCK_CORE_SPEC,
    TRANSFORM_CORE_SPEC,
    TRANSFORM_ECOMMERCE_JOIN_SPEC,
    WIDE_FLAT_SIZES,
)

SCENARIOS = [
    {
        "operation": "parse",
        "scenario": "flat",
        "json_column": "json_flat",
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "nested",
        "json_column": "json_nested",
        "targets": ["jsono"],
    },
    {
        "operation": "validate",
        "scenario": "flat",
        "json_column": "json_flat",
        "targets": ["jsono"],
    },
    {
        "operation": "validate",
        "scenario": "nested",
        "json_column": "json_nested",
        "targets": ["jsono"],
    },
    {
        "operation": "storage_size",
        "scenario": "nested",
        "json_column": "json_nested",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct",
        "scenario": "nested_typed",
        "size": "100k",
        "row_count": 100_000,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_roundtrip",
        "scenario": "nested_typed",
        "size": "100k",
        "row_count": 100_000,
        "targets": ["jsono"],
    },
    {
        "operation": "parse_struct_json_roundtrip",
        "scenario": "nested_typed",
        "size": "100k",
        "row_count": 100_000,
        "targets": ["jsono"],
    },
    {
        "operation": "transform",
        "scenario": "nested_core",
        "json_column": "json_nested",
        "spec": TRANSFORM_CORE_SPEC,
        "current_only": True,
        "targets": ["jsono"],
    },
    {
        "operation": "transform",
        "scenario": "ecommerce_join",
        "json_column": "json_nested",
        "spec": TRANSFORM_ECOMMERCE_JOIN_SPEC,
        "current_only": True,
        "targets": ["jsono"],
    },
    {
        "operation": "transform",
        "scenario": "flat_core",
        "json_column": "json_flat",
        "spec": PLUCK_CORE_SPEC,
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge",
        "scenario": "few_groups_ignore_nulls",
        "json_column": "json_flat",
        "group_col": "g1e1",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge_jsono",
        "scenario": "few_groups_ignore_nulls",
        "json_column": "json_flat",
        "group_col": "g1e1",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge",
        "scenario": "many_groups_ignore_nulls",
        "json_column": "json_flat",
        "group_col": "g1e4",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge_jsono",
        "scenario": "many_groups_ignore_nulls",
        "json_column": "json_flat",
        "group_col": "g1e4",
        "targets": ["jsono"],
    },
    {
        "operation": "optimizer_project",
        "scenario": "repeated_filter_project",
        "size": "100k",
        "json_column": "json_nested",
        "targets": ["jsono"],
    },
    {
        "operation": "merge_patch",
        "scenario": "nested_small_patch",
        "size": "10k",
        "json_column": "json_nested",
        "patch_object": {"event_name": "page_view"},
        "targets": ["jsono", "json"],
    },
    {
        "operation": "reshred",
        "scenario": "same_set",
        "size": "100k",
        "json_column": "json_flat",
        "source_spec": {"event_name": "VARCHAR", "user_id": "VARCHAR"},
        "target_spec": {"event_name": "VARCHAR", "user_id": "VARCHAR"},
        "targets": ["jsono"],
    },
    {
        "operation": "reshred",
        "scenario": "widening",
        "size": "100k",
        "json_column": "json_flat",
        "source_spec": {"event_name": "VARCHAR", "user_id": "VARCHAR"},
        "target_spec": {
            "event_name": "VARCHAR",
            "user_id": "VARCHAR",
            "session_id": "VARCHAR",
            "event_ts": "BIGINT",
        },
        "targets": ["jsono"],
    },
    {
        "operation": "reshred",
        "scenario": "narrowing",
        "size": "100k",
        "json_column": "json_flat",
        "source_spec": {
            "event_name": "VARCHAR",
            "user_id": "VARCHAR",
            "session_id": "VARCHAR",
            "event_ts": "BIGINT",
        },
        "target_spec": {"event_name": "VARCHAR", "user_id": "VARCHAR"},
        "targets": ["jsono"],
    },
    {
        "operation": "entries",
        "scenario": "flat_dotted",
        "size": "10k",
        "json_column": "json_flat",
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract",
        "scenario": "nested_core",
        "size": "10k",
        "json_column": "json_nested",
        "spec": EXTRACT_CORE_SPEC,
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract_jsono",
        "scenario": "nested_top_key",
        "size": "10k",
        "json_column": "json_nested",
        "path": "event_name",
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract_jsono",
        "scenario": "nested_jsonpath_object",
        "size": "10k",
        "json_column": "json_nested",
        "path": "$.page",
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract_jsono",
        "scenario": "nested_array_index",
        "size": "10k",
        "json_column": "json_nested",
        "base_path": "$.ec_items",
        "path": 0,
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract_string",
        "scenario": "nested_top_key",
        "size": "10k",
        "json_column": "json_nested",
        "path": "event_name",
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract_string",
        "scenario": "nested_jsonpath_scalar",
        "size": "10k",
        "json_column": "json_nested",
        "path": "$.page.page_url",
        "targets": ["jsono", "json"],
    },
    {
        "operation": "extract_string",
        "scenario": "nested_array_index",
        "size": "10k",
        "json_column": "json_nested",
        "base_path": "$.ec_items",
        "path": 0,
        "targets": ["jsono", "json"],
    },
    # Wide-flat page_view-class merge shape (~100 schema-stable scalar keys):
    # merge-family performance is shape-dependent, the nested merge scenarios
    # above do not represent it. Generate the dataset with:
    # uv run python bench/generate_data.py --kind wide_flat
    {
        "operation": "merge_patch",
        "scenario": "wide_flat_small_patch",
        "size": "100k",
        "row_count": WIDE_FLAT_SIZES["100k"],
        "data_file": DATA_DIR / "wide_flat_100k.parquet",
        "json_column": "json_wide_flat",
        "patch_object": {"event_name": "page_view_merged"},
        "targets": ["jsono", "json"],
    },
    {
        "operation": "group_merge_jsono",
        "scenario": "wide_flat_few_groups",
        "size": "100k",
        "row_count": WIDE_FLAT_SIZES["100k"],
        "data_file": DATA_DIR / "wide_flat_100k.parquet",
        "json_column": "json_wide_flat",
        "group_col": "g1e1",
        "targets": ["jsono"],
    },
    {
        "operation": "group_merge_jsono",
        "scenario": "wide_flat_many_groups",
        "size": "100k",
        "row_count": WIDE_FLAT_SIZES["100k"],
        "data_file": DATA_DIR / "wide_flat_100k.parquet",
        "json_column": "json_wide_flat",
        "group_col": "g1e4",
        "targets": ["jsono"],
    },
    {
        "operation": "parse",
        "scenario": "number_heavy",
        "size": "100k",
        "row_count": NUMBERS_SIZES["100k"],
        "data_file": DATA_DIR / "numbers_100k.parquet",
        "json_column": "json_numbers",
        "targets": ["jsono"],
    },
    {
        "operation": "parse_copy",
        "scenario": "number_heavy",
        "size": "100k",
        "row_count": NUMBERS_SIZES["100k"],
        "data_file": DATA_DIR / "numbers_100k.parquet",
        "json_column": "json_numbers",
        "copy_path": NUMBERS_PARSE_COPY_PATH,
        "copy_compression": FIELD_SAMPLE_JSONO_COMPRESSION,
        "copy_compression_level": FIELD_SAMPLE_JSONO_COMPRESSION_LEVEL,
        "copy_row_group_size": FIELD_SAMPLE_JSONO_ROW_GROUP_SIZE,
        "targets": ["jsono"],
    },
    {
        "operation": "validate",
        "scenario": "number_heavy",
        "size": "100k",
        "row_count": NUMBERS_SIZES["100k"],
        "data_file": DATA_DIR / "numbers_100k.parquet",
        "json_column": "json_numbers",
        "targets": ["jsono"],
    },
    {
        "operation": "storage_size",
        "scenario": "number_heavy",
        "size": "100k",
        "row_count": NUMBERS_SIZES["100k"],
        "data_file": DATA_DIR / "numbers_100k.parquet",
        "json_column": "json_numbers",
        "targets": ["jsono"],
    },
]
